name: coverage

on:
    push:
        branches:
            - main

env:
  TREE_DEPTH: 20

jobs:
    coveralls:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - run: yarn --frozen-lockfile
            - run: yarn download:snark-artifacts
            - run: yarn compile
            - run: yarn test:coverage

            - uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
